import type { Metadata } from "next";
import Aboutme from "@/components/Aboutme";
import "./globals.css";
import Skills from "@/components/Skills";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";
import HomeContent from "@/components/HomeContent";
import Projects from "@/components/Projects";

export const metadata: Metadata = {
  title: "AC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className="font-mono"
      >
        {/* <Navbar /> */}
        {children}
        <HomeContent />
        <Aboutme />
        <Skills />
        <Projects />
        <Contact />
        <Footer />
      </body>
    </html>
  );
}
